### ISSUE TITLE
Add meta description content to index.html and doc.html

### ISSUE THREAD

**Issue by siwalikm** [siwalikm/Flash#5]
## Checklist (won't be merged if they are not all ticked)
- [ ] Added meta desc. content in head section to `A test service to mock slow server responses`
- [ ] I didn't modify any test case 🔴
- [ ] I've ⭐️ the repository (or not, all up to you)
- [ ] And more importantly, I've had fun! 🍺
 
More about meta desc.: [url](https://developers.google.com/web/tools/lighthouse/audits/description)
